### PR TITLE
Update link syntax per BHL

### PR DESCRIPTION
**Pull request by osg-cat**

### CODE REVIEW

**Comment by osg-cat** [comment]
@brianhlin Like this?

**Comment by osg-cat** [comment]
I’m not sure what to make of the link-checker failures. Some were for Google documents, but some were for the internal link(s).

**Comment by brianhlin** [comment]
@osg-cat Linking to the root doc is always annoying and I may need to send out another email about handling it specifically (we also may have been doing it wrong all along).

Playing around with it locally, I think the right way to update your link is `[the overall OSG management structure](/)` but I have to verify that this works with the new MkDocs version.

**Comment by osg-cat** [comment]
So… I’m waiting on you, @brianhlin , before finishing this PR and working on other sites?

**Pull request merged**
